development:
  adapter: postgresql
  database: dev
  pool: 5
  timeout: 5000
  username: lbeier
  password:
test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: lbeier
  password: 

production:
  adapter: postgresql
  database: prod
  pool: 5
  timeout: 5000
