development:
  adapter: postgresql
  database: dev
  pool: 5
  timeout: 5000
  username: lbeier
  password: root
test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: lbeier
  password: root

production:
  adapter: postgresql
  database: prod
  pool: 5
  timeout: 5000
